
### Send POST request with body to create new patients
POST http://lb-9054a53d.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Sorunke Hassan kafka test with analytics account",
  "address": "Olomore,Abeokuta,Ogun State",
  "dateOfBirth": "2001-11-10",
  "email": "sorunkestestwithkafkaAnalytics@gmail.com",
  "registeredAddress": "2002-11-10"
}
